apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-deployment
  template:
    metadata:
      labels:
        app: springboot-deployment
    spec:
      containers:
        - name: springboot-deployment
          image: manojnanjundaswamy/springboot-deployment:latest
          ports:
            - containerPort: 8080
