apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-06-10T09:39:25Z"
  labels:
    app: springboot-deployment-pod
  name: springboot-deployment-pod
spec:
  containers:
    - env:
        - name: TERM
          value: xterm
      image: localhost/springboot-deployment:latest
      name: springboot-deployment
      ports:
        - containerPort: 8080
          hostPort: 8090
      stdin: true
      tty: true