apiVersion: v1
kind: Service
metadata:
  name: springboot-deployment-service
spec:
  type: NodePort
  selector:
    app: springboot-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
